apiVersion: v1
kind: Service
metadata:
  name: newapp-service
spec:
  selector:
    app: newapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 80      # Port on the container
