apiVersion: v1
kind: Service
metadata:
  name: newapp-service
spec:
  selector:
    app: newapp  # This should match the labels in your deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 80     # Port on the container
